# CONFIGURATION FILE 
# All paths are to be given without final slash.

# Path 
path0: '/Users/isler/OneDrive/imperial/RR/t106a/sims3d461/sim4/re36900/ma244/02C24P5m4/avg/post' 
path1: '/Users/isler/OneDrive/imperial/RR/t106a/sims3d461/sim4/re36900/ma244/02C24P5m4/avgM8TI12/post' 
path2: '/Users/isler/OneDrive/imperial/RR/t106a/sims3d461/sim4/re36900/ma244/02C24P5m4/avgM8TI2/post' 
path3: '/Users/isler/OneDrive/imperial/RR/t106a/sims3d461/sim4/re36900/ma244/02C24P5m4/avgM8TI32/post' 
pathTKE: '/Users/isler/OneDrive/imperial/RR/t106a/sims3d461/sim4/re36900/ma244/02C24P5m4/avgM8TI32/post' 
pathExp: '/Users/isler/OneDrive/imperial/RR/t106a/exp'
pathExpCf: '/Users/isler/OneDrive/imperial/RR/t106a/exp'
pathExpLoss: '/Users/isler/OneDrive/imperial/RR/t106a/exp'
pathExpTau: '/Users/isler/OneDrive/imperial/RR/t106a/exp'
pathExpTKE: '/Users/isler/OneDrive/imperial/RR/t106a/exp'
nfiles: 4 # how many compressible flow folders we have?
nfilesTKEdns: 3 

#Experiments nfiles
nfilesCp: 4
nfilesCf: 1
nfilesLoss: 6
nfilesTau: 4
nfilesTKE: 1

# File
fileF: 'wallAvg'
fileB: 'blade'
fileE: 'expCp'
fileECf: 'expCf'
fileETau: 'expTau'
fileETKE: 'expTKE'
fileEL: 'expLoss'
fileI: 'inlet'
fileO: 'exit'
filehist: 'hpoint'
filePSDUp: 'hpointUp'
fileTKE: 'TKE_down' #TKE_up 

# Routines
routine:
  phisical: False
  correlation: False
  psd: False
  tke: True

# blade
nfileBlade: 16

# exit 
nfileExit: 16

# inlet
nfileInlet: 16

# TKE 
nfileTKE: 1 # number of files 
npointsz: 15
npointsy: 80
pfreq: 1
qunt: 4 # quantity of TKE variables: tau11, tau22, tau33, tau12

# Spline data
spline: 606

# PSD data downstream
nfilepsd: 13 # number of psd files 
psdloc: 16 # location in the .his file (data)
psdNpoints: 16 # number of points in the psd file

# PSD data upstream
nfilepsdUp: 3 # number of psd files 
psdlocUp: 8 # location in the .his file (data)
psdNpointsUp: 8 # number of points in the psd file

# Correlation data
nfilecorr: 2 # number of correlation files 
npcorr: 16 # number of points in z-direction

#Non-dimensional parameters
spacedim: 3 
#gamma
gamma: 1.4
# Chord
C: 1 
# U inf
Uinf: 1
# Picth
Py: 0.799
# Axial chord
Cax: 0.859
# Dynamic viscosity
mu: [2.71003e-05,2.71003e-05,2.71003e-05,2.71003e-05] #2.69906e-05 #2.68456e-05, 2.72109e-05   
# pinf
pInf: 12.0965 # Pa
# rhoInf
rhoInf: 1.0 # Kg/m3
# Reference velocity
uInf: 1.0
# Gas constant
R: 12.0965
# Exit isentropic Mach number
Mach2is: 0.407
# ymin for wake loss
yminLoss: -1.79131
# ymin for tau 
yminTau: -1.378
# yminTauExp
yminTkeExp: -0.702381
# Lz
Lz: 0.1
# At P=3
dzplus: 0.0027777776666666667 #0.0083333333
dyplus: 3.236666666666667e-05 #0.971e-4
# Shift position
# wake loss = 202, tau = 12, tke = 5
shiftLoss: 202
shiftTau: 12
shiftTke: 74